# VacationPy
----

#### Note
* Instructions have been included for each segment. You do not have to follow them exactly, but they are included to help you think through the steps.

In [1]:
# Dependencies and Setup
import matplotlib.pyplot as plt
import pandas as pd
import numpy as np
import requests
import gmaps
import os

# Import API key
from api_keys import g_key

### Store Part I results into DataFrame
* Load the csv exported in Part I to a DataFrame

In [2]:
#importing saved csv files
cities = pd.read_csv("../output_data/cities.csv")
CityWeather = pd.read_csv("../output_data/CityWeather.csv")
DataforScatterplots = pd.read_csv("../output_data/DataforScatterplots.csv")

CityWeather.head()

,City,Country,Temperature,Humidity,Cloudiness,Windspeed,Date,Longitude,Latitude
0,Luwuk,ID,77.49,80,52,5.61,1592581443,122.79,-0.95
1,Hamilton,US,82.00,69,1,3.36,1592580663,-84.53,39.18
2,Yushu,CN,64.00,72,99,8.05,1592581443,126.53,44.80
3,Paamiut,GL,37.18,92,100,8.59,1592581016,-49.67,61.99
4,Charters Towers,AU,60.46,80,20,6.35,1592581075,146.27,-20.10

### Humidity Heatmap
* Configure gmaps.
* Use the Lat and Lng as locations and Humidity as the weight.
* Add Heatmap layer to map.

In [12]:
#setting city location, creating new dataframe only containing city lat/lng coords
citylocation = CityWeather[["Latitude", "Longitude"]]
#creating var containg humidity values
humidity = CityWeather["Humidity"]
#configuring google api key
gmaps.configure(api_key=g_key)
#Creating layout list to use later
layout = {
    'width': '1000px',
    'height': '600px',
    'border': '1px solid black',
    'padding': '1px'}
#creating gmaps figure
fig = gmaps.figure(map_type="TERRAIN", zoom_level=1.5, center=(0,0), layout=layout)
#creating heatmap layer to show humidity in dataframe locations
Humidity_layer = gmaps.heatmap_layer(citylocation, weights=humidity, 
                                 dissipating=False, max_intensity=100,
                                 point_radius= 1.5)
#adding heatmap layer to the figure
fig.add_layer(Humidity_layer)
fig

Figure(layout=FigureLayout(border='1px solid black', height='600px', padding='1px', width='1000px'))

### Create new DataFrame fitting weather criteria
* Narrow down the cities to fit weather conditions.
* Drop any rows will null values.

In [4]:
#setting filters for ideal weather vacation spots
Filtered_data = CityWeather.loc[CityWeather['Humidity']<=50]
Filtered_data = Filtered_data.loc[Filtered_data["Temperature"] >= 65]
Filtered_data = Filtered_data.loc[Filtered_data['Temperature'] <= 85]
Filtered_data = Filtered_data.loc[Filtered_data['Windspeed'] <= 10]
print(Filtered_data.count())
#showing filtered data
Filtered_data.head()

City           51
Country        50
Temperature    51
Humidity       51
Cloudiness     51
Windspeed      51
Date           51
Longitude      51
Latitude       51
dtype: int64

,City,Country,Temperature,Humidity,Cloudiness,Windspeed,Date,Longitude,Latitude
14,Ipor√°,BR,81.91,41,67,6.31,1592581446,-51.12,-16.44
43,Saint George,US,73.40,17,1,6.93,1592580674,-113.58,37.10
46,Cherskiy,RU,69.71,45,74,1.88,1592581451,161.30,68.75
48,Arraial do Cabo,BR,82.40,45,71,6.93,1592580851,-42.03,-22.97
55,Manono,CD,80.94,38,13,4.97,1592581453,27.42,-7.30

### Hotel Map
* Store into variable named `hotel_df`.
* Add a "Hotel Name" column to the DataFrame.
* Set parameters to search for hotels with 5000 meters.
* Hit the Google Places API for each city's coordinates.
* Store the first Hotel result into the DataFrame.
* Plot markers on top of the heatmap.

In [5]:
#creating new dataframe from the filtered dataframe
hotel_df= Filtered_data
#adding new empty columns to dataframe to create areas for new data from api to be added
hotel_df['Hotel Name'] = ""
hotel_df['Hotel Lat'] = ""
hotel_df['Hotel Lng'] = ""
hotel_df['Hotel Rating'] = ""
#setting parameters for api hotel search
params = {
    "radius": 50000,
    "types": "hotel",
    "keyword": "hotel",
    "key": g_key
    }
#creating loop with iterrows function to be able to add info to newly created rows
for index, row in hotel_df.iterrows():
    #specifing latitude values var
    lat = row["Latitude"]
    #specifing longidude values var
    lng = row["Longitude"]
    #specifing city name value var(only created for print output)
    city = row["City"]
    #creating new parameter for the city location coords
    params["location"] = f'{lat},{lng}'
    #setting the url for the api search
    apiurl = "https://maps.googleapis.com/maps/api/place/nearbysearch/json"
    #api request
    hotel_api = requests.get(apiurl, params=params)
    #making api request info in json format
    hotel_api = hotel_api.json()
    
    #exception to let know if hotel information for city list is not found, if found, hotel info added to dataframe(name, exact coords, and rating)
    try:
        hotel_df.loc[index, "Hotel Name"] = hotel_api["results"][0]["name"]
        hotel_df.loc[index, "Hotel Lat"] = hotel_api["results"][0]["geometry"]["location"]['lat']
        hotel_df.loc[index, "Hotel Lng"] = hotel_api["results"][0]["geometry"]["location"]['lng']
        hotel_df.loc[index, "Hotel Rating"] = hotel_api["results"][0]["rating"]
    #show what cities no information is found 
    except:
        print(f"Missing results for {city}, skipping entry")

hotel_df.head()

Missing results for Cherskiy, skipping entry
Missing results for Bukama, skipping entry
Missing results for Chokurdakh, skipping entry
Missing results for Srednekolymsk, skipping entry
Missing results for Belaya Gora, skipping entry

,City,Country,Temperature,Humidity,Cloudiness,Windspeed,Date,Longitude,Latitude,Hotel Name,Hotel Lat,Hotel Lng,Hotel Rating
14,Ipor√°,BR,81.91,41,67,6.31,1592581446,-51.12,-16.44,Grand Hotel,-16.4349,-51.1115,4.3
43,Saint George,US,73.40,17,1,6.93,1592580674,-113.58,37.10,Virgin River Hotel And Casino,36.8154,-114.067,3.9
46,Cherskiy,RU,69.71,45,74,1.88,1592581451,161.30,68.75,,,,
48,Arraial do Cabo,BR,82.40,45,71,6.93,1592580851,-42.03,-22.97,Vilarejo Praia Hotel,-22.5484,-41.974,4.5
55,Manono,CD,80.94,38,13,4.97,1592581453,27.42,-7.30,Hotel hewa bora,-7.29285,27.3958,0

In [17]:
#fill and get rid of empty/NaN values
nan_value = float("NaN")
hotel_df.replace("", nan_value, inplace=True)
hotel_df.dropna(subset=['Hotel Name'], inplace=True)
hotel_df

,City,Country,Temperature,Humidity,Cloudiness,Windspeed,Date,Longitude,Latitude,Hotel Name,Hotel Lat,Hotel Lng,Hotel Rating
14,Ipor√°,BR,81.91,41,67,6.31,1592581446,-51.12,-16.44,Grand Hotel,-16.434881,-51.111483,4.3
43,Saint George,US,73.40,17,1,6.93,1592580674,-113.58,37.10,Virgin River Hotel And Casino,36.815354,-114.066823,3.9
48,Arraial do Cabo,BR,82.40,45,71,6.93,1592580851,-42.03,-22.97,Vilarejo Praia Hotel,-22.548389,-41.973990,4.5
55,Manono,CD,80.94,38,13,4.97,1592581453,27.42,-7.30,Hotel hewa bora,-7.292855,27.395825,0.0
75,Saskylakh,RU,69.24,47,39,6.49,1592580872,114.08,71.92,Saskylakh Aeroport,71.929303,114.087797,4.5
84,Sagarejo,GE,78.80,41,75,8.05,1592581462,45.33,41.73,hotel vaki,41.727335,44.728051,4.4
100,L√ºderitz,NaN,80.60,21,0,9.17,1592580940,15.16,-26.65,Kairos Cottage,-26.636481,15.152356,4.5
119,Port Elizabeth,ZA,75.20,29,0,3.36,1592581014,25.57,-33.92,The Beach Hotel,-33.982086,25.658955,4.3
123,Saint-Fran√ßois,FR,71.60,43,52,6.93,1592581471,3.91,46.42,H√¥tel de Grignan,46.121134,3.420729,4.5
128,Hermanus,ZA,68.00,48,0,5.99,1592581179,19.23,-34.42,The Marine Hermanus,-34.418038,19.244810,4.5
167,Mafinga,TZ,73.53,43,27,2.53,1592581478,35.07,-7.25,Mabata Makali Luxury Tented Camp,-7.631066,35.144841,3.5
176,Guanambi,BR,82.74,46,66,9.57,1592581424,-42.78,-14.22,Hotel Caetit√©,-14.064950,-42.485318,4.3
201,Marsabit,KE,74.50,47,57,8.46,1592580921,37.99,2.33,Jirime Hotel & Resort,2.360824,38.006365,3.9
209,Szentgotth√°rd,HU,72.00,32,64,7.00,1592581486,16.27,46.95,Falkensteiner Balance Resort Stegersbach,47.170506,16.151484,4.6
228,≈Ωivinice,BA,82.40,34,20,4.70,1592581488,18.65,44.45,Stani≈°iƒái Ethno Village,44.784349,19.278845,4.7
258,Almaznyy,RU,82.40,34,20,4.47,1592581494,40.05,48.04,Art Otel',48.307645,40.282067,4.3
291,Yangi Marg`ilon,UZ,84.20,20,15,2.24,1592581499,71.72,40.43,Voyage Hotel,40.373001,71.789942,4.9
302,Af≈üin,TR,68.54,48,81,4.34,1592581500,36.91,38.25,Eyl√ºl Bungalow,38.049342,36.476829,4.3
308,H√§meenlinna,FI,82.00,50,40,7.67,1592581502,24.46,61.00,Aulangon Rantahuvila,61.030938,24.473775,4.6
328,√Ömot,NO,82.00,37,62,1.99,1592581505,7.99,59.57,Tuddal H√∏yfjellshotel AS,59.793881,8.747578,4.7
330,Menongue,AO,68.56,33,23,4.65,1592581505,17.69,-14.66,Rio Cuebe Lodge,-14.565030,17.742644,0.0
341,Malartic,CA,80.01,44,5,4.70,1592581064,-78.13,48.13,H√¥tel Forestel,48.097691,-77.750256,4.3
345,Farmington,US,72.00,20,1,6.93,1592581508,-108.22,36.73,Home2 Suites by Hilton Farmington/ Bloomfield,36.723108,-108.158914,4.5
372,Naples,IT,79.00,50,20,3.36,1592581513,14.25,40.83,Renaissance Naples Hotel Mediterraneo,40.841046,14.250598,4.4
408,Kashgar,CN,82.40,12,75,6.71,1592581517,75.98,39.45,Radisson Blu Hotel Kashgar,39.447990,76.003120,4.6
417,Kiryat Gat,IL,80.01,33,0,1.01,1592580864,34.76,31.61,King David Hotel,31.774378,35.222617,4.6
431,Msanga,TZ,75.20,50,40,9.17,1592581526,36.03,-6.05,New Dodoma Hotel,-6.184437,35.749249,3.7
440,Ludvika,SE,80.01,39,62,8.01,1592581527,15.19,60.15,Best Western Gustaf Wasa Hotel,60.482014,15.428786,4.0
444,Vanga≈æi,LV,84.20,42,63,6.93,1592581528,24.55,57.09,"Radisson Blu Latvija Conference & Spa Hotel, Riga",56.954881,24.117550,4.5
449,Karratha,AU,72.00,47,0,4.92,1592581064,116.85,-20.74,Best Western Plus The Ranges Karratha,-20.752692,116.848313,4.6
472,Deyang,CN,81.00,1,100,0.76,1592581532,104.38,31.13,Jiuzhaigou Hotel,30.685995,104.034409,3.5
478,Kumluca,TR,83.12,43,19,1.74,1592581533,30.29,36.37,Barut Kemer,36.609840,30.558802,4.8
479,Cassil√¢ndia,BR,82.35,45,1,8.55,1592581027,-51.73,-19.11,Hotel Rafa Cassil√¢ndia,-19.113682,-51.733122,4.7
480,√ñstersund,SE,73.40,40,1,5.82,1592581015,14.64,63.18,Clarion Hotel Grand √ñstersund,63.179839,14.636200,4.2
487,Dalhousie,IN,72.34,30,33,7.25,1592581534,75.98,32.53,BrijVilla,32.537090,75.968670,4.7
492,Quba,AZ,70.57,39,0,0.56,1592581535,48.52,41.36,Shahdag Hotel & Spa,41.319558,48.135995,4.5
502,Lodja,CD,82.60,41,74,1.41,1592581537,23.43,-3.48,SANDO HOTEL,-3.526782,23.593667,4.7
503,Kamenka,RU,82.99,43,1,3.00,1592581537,42.77,51.32,Hotel Borisoglebsk,51.365998,42.080249,3.7
525,Stranda,NO,79.00,36,98,4.05,1592581541,6.94,62.31,Grande Fjord Hotel,62.115876,7.183561,4.7
527,Tinqueux,FR,71.60,46,48,9.17,1592581541,3.98,49.25,Ch√¢teau d'√âtoges,48.881903,3.851287,4.6
535,Pishin,PK,80.01,13,0,3.96,1592581542,67.00,30.58,Serena Hotel Quetta,30.204409,67.012245,4.3
542,Mount Isa,AU,71.60,40,75,5.82,1592581543,139.50,-20.73,Abacus Motel,-20.699471,139.486778,4.6
547,Matagami,CA,82.40,39,1,9.17,1592581544,-77.63,49.75,H√¥tel Matagami,49.756264,-77.633705,4.0
556,PƒÅveh,IR,72.46,23,0,5.55,1592581546,46.36,35.04,Aweser resorts,35.216765,46.187531,4.8
557,Jatai,BR,80.53,41,76,7.72,1592581546,-51.71,-17.88,Hotel Fazenda Thermas Bonsucesso,-17.817524,-51.771575,4.5
570,Correntina,BR,84.94,36,0,7.16,1592581550,-44.64,-13.34,Hotel Portal do Corrente,-13.391142,-44.205955,4.5

In [7]:
# NOTE: Do not change any of the code in this cell
#added a line to the box template to add the hotel rating to the info box!!!
# Using the template add the hotel marks to the heatmap
info_box_template = """
<dl>
<dt>Name</dt><dd>{Hotel Name}</dd>
<dt>City</dt><dd>{City}</dd>
<dt>Country</dt><dd>{Country}</dd>
<dt>Hotel Rating</dt><dd>{Hotel Rating}</dd>
</dl>
"""
# Store the DataFrame Row
# NOTE: be sure to update with your DataFrame name
hotel_info = [info_box_template.format(**row) for index, row in hotel_df.iterrows()]
locations = hotel_df[["Hotel Lat", "Hotel Lng"]]

In [8]:
# Add marker layer ontop of heat map
markers = gmaps.marker_layer(locations, info_box_content=hotel_info)
fig.add_layer(markers)

# Display figure
fig

Figure(layout=FigureLayout(border='1px solid black', height='600px', padding='1px', width='1000px'))